#spring.application.name=Movie
# database ?? ??
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    #    ?? PC? ????? Database??? ?? ???.
    url: jdbc:mysql://127.0.0.1:3306/movie_db?createDatabaseIfNotExist=true
    #    mysql? ??? ??? ?? ??? ?? ???.
    username: root
    password: 1234
  thymeleaf:
    cache: false

  # spring data jpa ??
  jpa:
    database-platform: org.hibernate.dialect.MySQL8Dialect
    open-in-view: false
    show-sql: true
    hibernate:
      # DB 새로 만들 거면 create 로 할 것
      ddl-auto:
    properties:
      hibernate:
        #        show_sql: true
        format_sql: true
        use_sql_comments: true # querydsl에서 jpql 보고 싶다면
        dialect: org.hibernate.dialect.MySQL8Dialect

logging.level:
  org.hibernate.SQL: debug



